haccanhvien/urls.py
from django.urls import path

from . import views
from .admin import dich_vu_adminsite, san_pham_adminsite

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/dichvu/", dich_vu_adminsite.urls),
    path("admin/sanpham/", san_pham_adminsite.urls),
    path("so-do-du-an/", views.ban_hang, name="so-do-du-an"),
    path("order/", views.dat_hang, name="order"),
    path("order/<int:customer_id>/", views.dat_hang, name="existing_customer_order"),
    path("quan-li-don-hang/", views.quan_li_don_hang, name="quan_li_don_hang"),
    path("quan-li-don-hang/<int:ma_don_hang>/<slug:trang_thai>",
         views.quan_li_don_hang, name="doi_trang_thai_don_hang"),
    path("thong-tin-nguoi-mat/<int:moid>", views.thong_tin_nguoi_mat, name="thong_tin_nguoi_mat"),
    path("thong-tin-nguoi-mat/add/<int:moid>", views.add_nguoi_mat, name="add_nguoi_mat"),
    path("quan-li-giay-chung-nhan/", views.quan_li_giay_chung_nhan, name="quan_li_giay_chung_nhan"),
    path("quan-li-giay-chung-nhan/<int:giay_chung_nhan_id>/<slug:trang_thai>",
         views.quan_li_giay_chung_nhan, name="doi_trang_thai_giay_chung_nhan"),
    path('thong-ke/<slug:from_date>/<slug:to_date>', views.thong_ke_don_hang, name='thong_ke'),
    path('thong-ke/', views.thong_ke_don_hang, name='xem_thong_ke'),
]

hcv_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("haccanhvien/", include("haccanhvien.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

haccanhvien/models/dich_vu.py
from django.db import models


class LoaiDichVu(models.Model):
    ten_loai_dich_vu = models.CharField("Loại dịch vụ", name="ten_loai_dich_vu", unique=True, max_length=256)
    ma_loai_dich_vu = models.CharField("Mã loại dịch vụ", name="ma_loai_dich_vu", unique=True, max_length=256)
    mieu_ta = models.TextField(verbose_name="Miêu tả", name="mieu_ta", blank=True, null=True)

    class Meta:
        verbose_name = "Loại Dịch vụ"
        verbose_name_plural = "Loại Dịch vụ"

    def __str__(self) -> str:
        return self.ten_loai_dich_vu

    def save(self, *args, **kwargs) -> None:
        """Override the save method to update the foreign key value when it is changed
        """
        # Get the old object before saving the changes
        try:
            old_obj = LoaiDichVu.objects.get(pk=self.pk)
        except LoaiDichVu.DoesNotExist:
            old_obj = None

        # Call the original save method
        super().save(*args, **kwargs)

        # Update the foreign key in the related model
        if old_obj and old_obj.ma_loai_dich_vu != self.ma_loai_dich_vu:
            DichVu.objects.filter(ma_loai_dich_vu=old_obj.ma_loai_dich_vu).update(
                ma_loai_dich_vu=self.ma_loai_dich_vu)


class ThanhPhanDichVu(models.Model):
    ten_thanh_phan = models.CharField(verbose_name="Tên thành phần", name="ten_thanh_phan", unique=True, max_length=256)
    ma_thanh_phan = models.CharField(verbose_name="Mã thành phần", name="ma_thanh_phan", unique=True, max_length=256)
    ma_loai_dich_vu = models.ForeignKey(LoaiDichVu, on_delete=models.CASCADE,
                                        verbose_name="Mã loại dịch vụ", to_field="ma_loai_dich_vu")
    mieu_ta = models.TextField(verbose_name="Miêu tả", name="mieu_ta", blank=True, null=True)

    class Meta:
        verbose_name = "Thành phần Dịch vụ"
        verbose_name_plural = "Thành phần Dịch vụ"

    def __str__(self) -> str:
        return self.ten_thanh_phan


class DichVu(models.Model):
    ten_dich_vu = models.CharField(verbose_name="Tên dịch vụ", name="ten_dich_vu", unique=True, max_length=256)
    ma_dich_vu = models.CharField(verbose_name="Mã dịch vụ", name="ma_dich_vu", unique=True, max_length=256)
    loai_dich_vu = models.ForeignKey(LoaiDichVu, on_delete=models.CASCADE,
                                     to_field="ma_loai_dich_vu", verbose_name="Loại dịch vụ")
    danh_sach_thanh_phan = models.ManyToManyField(
        ThanhPhanDichVu, verbose_name="Danh sách thành phần", null=True, blank=True)
    mieu_ta = models.TextField(verbose_name="Miêu tả", name="mieu_ta", blank=True, null=True)

    class Meta:
        verbose_name = "Dịch vụ"
        verbose_name_plural = "Dịch vụ"

    def __str__(self) -> str:
        return self.ten_dich_vu

haccanhvien/models/khach_hang.py
from django.db import models

from .san_pham import Mo, TinhTrangMo


class KhachMua(models.Model):
    ma_khach_hang = models.AutoField(verbose_name="Mã khách hàng", primary_key=True)
    ten_khach = models.CharField(verbose_name="Têm khách hàng", blank=False, max_length=256)
    CCCD = models.CharField(verbose_name="Số CMND/CCCD", blank=False, max_length=20)
    so_dien_thoai = models.CharField(verbose_name="Số điện thoại", max_length=20)
    dia_chi = models.TextField(verbose_name="Địa chỉ")

    class Meta:
        verbose_name = "Khách mua hàng"
        verbose_name_plural = "Khách mua hàng"

    def __str__(self) -> str:
        return f"{self.ten_khach} - SDT: {self.so_dien_thoai}"


class KhachMat(models.Model):
    ma_khach_hang = models.AutoField(verbose_name="Mã khách hàng", primary_key=True)
    ten_khach = models.CharField(verbose_name="Tên khách", blank=False, max_length=256)
    ngay_mat = models.DateField(verbose_name="Ngày mất", blank=False)
    mo = models.ForeignKey(Mo, verbose_name="Mộ chôn", blank=False, on_delete=models.CASCADE)
    thong_tin_khac = models.TextField(verbose_name="Thông tin khác", blank=True)

    class Meta:
        verbose_name = "Khách sử dụng mộ"
        verbose_name_plural = "Khách sử dụng mộ"

    def __str__(self) -> str:
        return f"{self.ten_khach} - Ngày mất: {self.ngay_mat}"

    def save(self, *args, **kwargs) -> None:
        super().save(*args, **kwargs)

        # Change the status of Mo to DaSuDung
        if self.mo.tinh_trang_mo.ma_tinh_trang != "DSD":
            self.mo.tinh_trang_mo = TinhTrangMo.objects.get(ma_tinh_trang="DSD")
        self.mo.save()


class KyUc(models.Model):
    khach_hang = models.OneToOneField(KhachMat, on_delete=models.CASCADE, verbose_name="Khách hàng")

    class Meta:
        verbose_name = "Ký ức"
        verbose_name_plural = "Ký ức"

    def __str__(self) -> str:
        return f"Ký ức Khách: {self.khach_hang}"


class AnhKyUc(models.Model):
    ma_ky_uc = models.ForeignKey(KyUc, on_delete=models.CASCADE, verbose_name="Ký ức")
    image = models.ImageField("Ảnh", name="image", upload_to="images/")

    class Meta:
        verbose_name = "Ảnh ký ức"
        verbose_name_plural = "Ảnh ký ức"

haccanhvien/forms.py
from django.forms import ModelForm, widgets

from .models.khach_hang import KhachMat, KhachMua
from .models.sales import DonHang


class KhachMuaForm(ModelForm):
    class Meta:
        model = KhachMua
        fields = '__all__'


class KhachMatForm(ModelForm):
    class Meta:
        model = KhachMat
        fields = "__all__"
        exclude = ["mo"]
        widgets = {
            "ngay_mat": widgets.DateInput(attrs={"type": "date"}),
            "ten_khach": widgets.TextInput(attrs={"class": "form-control"}),
            "thong_tin_khac": widgets.Textarea(attrs={"class": "form-control"}),
        }
class DonHangForm(ModelForm):
    class Meta:
        model = DonHang
        exclude = ["khach_mua"]
        widgets = {
            "ngay_giao_dich": widgets.DateInput(attrs={"type": "date"})
        }

haccanhvien/views.py
from collections import defaultdict
from datetime import datetime

from django.core.files.uploadedfile import SimpleUploadedFile
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_http_methods

from .forms import DonHangForm, KhachMatForm, KhachMuaForm
from .models.dich_vu import DichVu
from .models.khach_hang import AnhKyUc, KhachMat, KhachMua, KyUc
from .models.sales import DonHang, GiayChungNhan
from .models.san_pham import LoaiSanPham, Mo, TinhTrangMo


def get_all_mo_in_grouped_objects(filter_dict=None):
    if filter_dict is None:
        filter_dict = {}
    all_mo = Mo.objects.filter(**filter_dict)

    grouped_objects = []

    for obj in all_mo:
        grouped_objects.append((obj.hang, obj.cot, obj))

    context = {"grouped_objects": grouped_objects}
    return context

# Create your views here.


def index(request):
    return HttpResponse("Hello, world! Small step towards a big system!")


def ban_hang(request):
    context = get_all_mo_in_grouped_objects()

    all_ma_san_pham = LoaiSanPham.objects.all()
    context["all_ma_san_pham"] = all_ma_san_pham

    return render(request, "thong_tin_du_an.html", context)


def dat_hang(request, customer_id=None, mo_id=None):
    if request.method == "POST":
        if customer_id:
            # Handle creating a new order for the existing customer
            khach_mua = KhachMua.objects.get(pk=customer_id)
            donhang_form = DonHangForm(request.POST, prefix="donhang")
            if donhang_form.is_valid():
                donhang = donhang_form.save(commit=False)
                donhang.khach_mua = khach_mua
                donhang.save()
                danh_sach_dich_vu = donhang_form.cleaned_data["danh_sach_dich_vu"]
                donhang.danh_sach_dich_vu.set(danh_sach_dich_vu)
                return redirect("order")  # Redirect to the same page to avoid resubmitting the form
        else:
            # Handle creating a new customer and order
            khach_mua_form = KhachMuaForm(request.POST, prefix="khachhang")
            donhang_form = DonHangForm(request.POST, prefix="donhang")

            if khach_mua_form.is_valid() and donhang_form.is_valid():
                khachhang = khach_mua_form.save()
                donhang = donhang_form.save(commit=False)
                donhang.khach_mua = khachhang
                donhang.save()
                danh_sach_dich_vu = donhang_form.cleaned_data["danh_sach_dich_vu"]
                donhang.danh_sach_dich_vu.set(danh_sach_dich_vu)
                return redirect("order")  # Redirect to the same page to avoid resubmitting the form
    else:
        khach_mua_form = KhachMuaForm(prefix="khachhang")
        donhang_form = DonHangForm(prefix="donhang")

    customers = KhachMua.objects.all()
    all_dich_vu = DichVu.objects.all()
    return render(request, "dat_hang.html", {"khach_mua_form": khach_mua_form, "donhang_form": donhang_form, "customers": customers, "all_dich_vu": all_dich_vu})


@require_http_methods(["GET", "POST"])
def quan_li_don_hang(request, ma_don_hang=None, trang_thai=None):
    if request.method == "GET":
        context = get_all_mo_in_grouped_objects()
        context["all_don_hang"] = {
            "don_hang_dang_giao_dich": DonHang.objects.filter(trang_thai=DonHang.DANG_CHO),
            "don_hang_da_hoan_tat": DonHang.objects.filter(trang_thai=DonHang.HOAN_TAT)
        }
        return render(request, "quan_li_don_hang.html", context)
    elif request.method == "POST":
        if ma_don_hang and trang_thai:
            don_hang = DonHang.objects.get(ma_don_hang=ma_don_hang)
            valid_trang_thai = [choice[0] for choice in DonHang.TRANG_THAI]

            if trang_thai not in valid_trang_thai:
                return f"Error, cannot set trang thai of Don hang to {trang_thai}"

            don_hang.trang_thai = trang_thai
            don_hang.save()

            return redirect("quan_li_don_hang")


@require_http_methods(["GET", "POST"])
def add_nguoi_mat(request, moid: int):
    if request.method == "GET":
        khach_mat_form = KhachMatForm(prefix="khachmat")
        return render(request, "them_thong_tin_nguoi_mat.html", {"khach_mat_form": khach_mat_form})
    else:
        khach_mat_form = KhachMatForm(request.POST, prefix="khachmat")
        if khach_mat_form.is_valid():
            mo = Mo.objects.get(pk=moid)
            khach_mat = khach_mat_form.save(commit=False)
            khach_mat.mo = mo
            khach_mat.save()

            if "file-upload" in request.FILES:
                ky_uc = KyUc(khach_hang=khach_mat)
                ky_uc.save()
                files = request.FILES.getlist('file-upload')
                for f in files:
                    # Save the uploaded file
                    img = SimpleUploadedFile(f.name, f.read())
                    anh_ky_uc = AnhKyUc(ma_ky_uc=ky_uc, image=img)
                    anh_ky_uc.save()

            return redirect("so-do-du-an")


@require_http_methods(["GET"])
def thong_tin_nguoi_mat(request, moid: int):
    context = {}
    mo = Mo.objects.get(pk=moid)
    cac_khach_mat = KhachMat.objects.filter(mo=mo)

    context["cac_khach_mat"] = cac_khach_mat
    context["mo"] = mo
    return render(request, "thong_tin_nguoi_mat.html", context)


@require_http_methods(["GET", "POST"])
def quan_li_giay_chung_nhan(request, giay_chung_nhan_id=None, trang_thai=None):
    if request.method == "GET":
        context = get_all_mo_in_grouped_objects()
        context["all_giay_chung_nhan"] = {
            "giay_chung_nhan_dang_cho": GiayChungNhan.objects.filter(trang_thai=GiayChungNhan.DANG_CHO),
            "giay_chung_nhan_da_hoan_tat": GiayChungNhan.objects.filter(trang_thai=GiayChungNhan.HOAN_TAT)
        }
        return render(request, "giay_chung_nhan.html", context)
    elif request.method == "POST":
        if giay_chung_nhan_id and trang_thai:
            giay_chung_nhan = GiayChungNhan.objects.get(pk=giay_chung_nhan_id)
            valid_trang_thai = [choice[0] for choice in GiayChungNhan.TRANG_THAI]

            if trang_thai not in valid_trang_thai:
                return f"Error, cannot set trang thai of Don hang to {trang_thai}"

            giay_chung_nhan.trang_thai = trang_thai
            giay_chung_nhan.save()

            # If trang thai change to DANG_CHO, the associated Mo should be marked as Dang Giao Dich, not Da Ban
            mo = giay_chung_nhan.don_hang.mo
            if trang_thai == "DANG_CHO" and mo.tinh_trang_mo == TinhTrangMo.objects.get(ma_tinh_trang="DB"):
                mo.tinh_trang_mo = TinhTrangMo.objects.get(ma_tinh_trang="DGD")
                mo.save()

            return redirect("quan_li_giay_chung_nhan")


def thong_ke_don_hang(request, from_date=None, to_date=None):
    if from_date is None or to_date is None:
        return render(request, "thong_ke_don_hang.html")

    # Parse the dates from string to datetime objects
    from_date_obj = datetime.strptime(from_date, '%Y-%m-%d')
    to_date_obj = datetime.strptime(to_date, '%Y-%m-%d')

    # Query the 'DonHang' model instances within the date range
    dach_sach_don_hang = DonHang.objects.filter(
        Q(ngay_giao_dich__gte=from_date_obj) & Q(ngay_giao_dich__lte=to_date_obj)
    )

    all_mo = Mo.objects.all()

    total_mo = len(all_mo)
    used_mo = len(Mo.objects.filter(tinh_trang_mo=TinhTrangMo.objects.get(ma_tinh_trang="DSD")))

    # perform some simple stats
    total_value = 0
    dich_vu_count = defaultdict(int)
    for donhang in dach_sach_don_hang:
        total_value += int(donhang.gia_tri_don_hang)
        for dich_vu in donhang.danh_sach_dich_vu.all():
            dich_vu_count[dich_vu] += 1

    context = {
        "dich_vu_count": dict(dich_vu_count),
        "total_value": total_value,
        "from_date": from_date_obj.strftime("%d-%m-%Y"),
        "to_date": to_date_obj.strftime("%d-%m-%Y"),
        "total_mo": total_mo,
        "used_mo": used_mo
    }

    return render(request, "thong_ke_don_hang.html", context)

haccanhvien/templates/ban_hang.html
{% extends "project_plan.html" %}
{% load static %}

{% block title %}Bán Hàng{% endblock %}
{% block heading %}Trang bán hàng{% endblock %}

{% block side_info %}
<h2>Danh sách các loại sản phẩm</h2>
<div class="accordion" id="danh_sach_ma_san_pham">
    {% for ma_san_pham in all_ma_san_pham %}
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ ma_san_pham.ma_san_pham }}"
                    aria-expanded="true" aria-controls="collapse{{ ma_san_pham.ma_san_pham }}">
                    {{ ma_san_pham.ten_san_pham }}
                </button>
            </h2>
            <div id="collapse{{ ma_san_pham.ma_san_pham }}" class="accordion-collapse collapse show">
                <div class="accordion-body">
                    {{ ma_san_pham.mieu_ta }}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

haccanhvien/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {%block extrahead %}{% endblock %}
</head>

<body>

    <div class="header">
        <h1>{% block heading %}{% endblock %}</h1>
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>

haccanhvien/templates/dat_hang.html
{% extends "base.html" %}
{% load static %}

{% block title %}Tạo đơn hàng{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-8">
                <h1>Tạo đơn đặt hàng mới</h1>
                <label>Loại khách hàng</label>
                <select id="customer_type" name="customer_type">
                    <option value="">Vui lòng chọn loại khách hàng</option>
                    <option value="new">Khách hàng mới</option>
                    <option value="existing">Khách hàng cũ</option>
                </select>

                <form id="main_form" method="POST" action="">
                    {% csrf_token %}
                    <div id="new_customer" style="display:none;">
                        <h2>Tạo khách hàng mới</h2>
                        {{ khach_mua_form.as_div }}
                    </div>
                    <div id="existing_customer" style="display:none;">
                        <h2>Thông tin khách hàng cũ</h2>
                        <label>Khách hàng</label>
                        <select id="existing_customer_select" name="existing_customer_select">
                            <option value="">--Vui lòng chọn 1 khách hàng trong danh sách--</option>
                            {% for customer in customers %}
                                <option value="{{ customer.pk }}">{{ customer }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <h2>Thông tin đơn hàng</h2>
                        {{ donhang_form.as_div }}
                    </div>
                    <button type="submit">Xác nhận</button>
                </form>
            </div>
            <div class="col-4">
                <h2>Miêu tả dịch vụ</h2>
                <div class="accordion" id="danh_sach_dich_vu">
                    {% for dich_vu in all_dich_vu %}
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapse{{ dich_vu.ma_dich_vu }}" aria-expanded="true"
                                aria-controls="collapse{{ dich_vu.ma_dich_vu }}">
                                {{ dich_vu.ten_dich_vu }}
                            </button>
                        </h2>
                        <div id="collapse{{ dich_vu.ma_dich_vu }}" class="accordion-collapse collapse show">
                            <div class="accordion-body">
                                <p>Loại dịch vụ: {{ dich_vu.loai_dich_vu }}</p>
                                <p>Thành phần trong dịch vụ: {{ dich_vu.danh_sach_thanh_phan.all|join:", " }}</p>
                                <p>Miêu tả: {{ dich_vu.mieu_ta }}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/order_script.js' %}"></script>
{% endblock %}

haccanhvien/templates/giay_chung_nhan.html
{% extends "project_plan.html" %}
{% load static %}

{% block title %}Quản lí đơn hàng{% endblock %}
{% block heading %}Trang quản lí Giấy chứng nhận{% endblock %}

{% block side_info %}
{% for tinh_trang, danh_sach_giay_chung_nhan in all_giay_chung_nhan.items %}
<h2>Danh sách Giấy chứng nhận {% if tinh_trang == "giay_chung_nhan_dang_cho" %}đang chờ xử lí{% else %}đã hoàn tất{% endif %}
</h2>
<div class="accordion" id="{{ tinh_trang }}">
    {% for giay_chung_nhan in danh_sach_giay_chung_nhan %}
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapse{{ giay_chung_nhan.pk }}" aria-expanded="true"
                aria-controls="collapse{{ giay_chung_nhan.pk }}">
                {{ giay_chung_nhan }}
            </button>
        </h2>
        <div id="collapse{{ giay_chung_nhan.pk }}" class="accordion-collapse collapse hide">
            <div class="accordion-body">
                <p>Tên khách hàng: {{ giay_chung_nhan.don_hang.khach_mua }}</p>
                <p>Mộ: {{ giay_chung_nhan.don_hang.mo }}</p>
                <p>Ngày giao dịch: {{ giay_chung_nhan.don_hang.ngay_giao_dich }}</p>
                <form method="post"
                    action="{{ giay_chung_nhan.pk }}/{% if tinh_trang == 'giay_chung_nhan_dang_cho' %}HOAN_TAT{% else %}DANG_CHO{% endif %}">
                    {% csrf_token %}
                    {% if tinh_trang == "giay_chung_nhan_dang_cho" %}
                    <button type="submit" class="btn btn-primary">Duyệt</button>
                    {% else %}
                    <button type="submit" class="btn btn-danger">Chưa duyệt</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    {% endfor%}
</div>
{% endfor %}
{% endblock %}

haccanhvien/templates/quan_li_don_hang.html
{% extends "project_plan.html" %}
{% load static %}

{% block title %}Quản lí đơn hàng{% endblock %}
{% block heading %}Trang quản lí đơn hàng{% endblock %}

{% block side_info %}
{% for loai_don_hang, danh_sach_don_hang in all_don_hang.items %}
    <h2>Danh sách Đơn hàng {% if loai_don_hang == "don_hang_dang_giao_dich" %}đang chờ xử lí{% else %}đã hoàn tất{% endif %}</h2>
    <div class="accordion" id="{{ loai_don_hang }}">
        {% for don_hang in danh_sach_don_hang %}
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapse{{ don_hang.ma_don_hang }}" aria-expanded="true"
                        aria-controls="collapse{{ don_hang.ma_don_hang }}">
                        {{ don_hang }}
                    </button>
                </h2>
                <div id="collapse{{ don_hang.ma_don_hang }}" class="accordion-collapse collapse hide">
                    <div class="accordion-body">
                        <p>Tên khách hàng: {{ don_hang.khach_mua }}</p>
                        <p>Mộ: {{ don_hang.mo }}</p>
                        <p>Ngày giao dịch: {{ don_hang.ngay_giao_dich }}</p>
                        <p>Danh sách dịch vụ: {{ don_hang.danh_sach_dich_vu.all|join:", " }}</p>
                        <p>Giá trị đơn hàng: {{ don_hang.gia_tri_don_hang }}</p>
                        <form method="post" action="{{don_hang.ma_don_hang}}/{% if loai_don_hang == 'don_hang_dang_giao_dich' %}HOAN_TAT{% else %}DANG_CHO{% endif %}">
                            {% csrf_token %}
                            {% if loai_don_hang == "don_hang_dang_giao_dich" %}
                            <button type="submit" class="btn btn-primary">Hoàn tất</button>
                            {% else %}
                            <button type="submit" class="btn btn-danger">Chưa hoàn tất</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        {% endfor%}
    </div>
{% endfor %}
{% endblock %}

haccanhvien/templates/thong_tin_nguoi_mat.html
{% extends "base.html" %}
{% load static %}

{% block title %}Thông tin người mất{% endblock %}

{% block content %}
<div class="container">
    <h1>Thông tin người mất</h1>
    <h2>{{ mo }}</h2>
    <ul class="list-group">
        {% for khach_hang in cac_khach_mat %}
        <li class="list-group-item">
            <div class="container">
                <h2>Tên khách hàng: {{ khach_hang.ten_khach }}</h2>
                <p>Ngày mất: {{ khach_hang.ngay_mat }}</p>
                {% if khach_hang.kyuc %}
                    <h2>Miền ký ức</h2>
                    <div id="carouselExample" class="carousel slide" style="background-color: grey; height: 800px;">
                        <div class="carousel-inner">
                            {% for anh_ky_uc in khach_hang.kyuc.anhkyuc_set.all %}
                            {% if forloop.first %}
                            <div class="carousel-item active">
                            {% else %}
                            <div class="carousel-item">
                            {% endif %}
                                <img src="{{ anh_ky_uc.image.url }}" class="d-block mx-auto img-fluid" alt="..." style="object-fit: cover; height: 800px;">
                            </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}